spring:
  application:
    name: BankSystem
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: postgres
  jakarta:
    persistence:
      jdbc:
        url: jdbc:postgresql://localhost:5432/bank
  jpa:
    hibernate:
      ddl-auto: update
      hbm2ddl:
        import_files: ddl.sql
    show-sql: true
